Avoid undefined NPY_INTERNAL_BUILD NumPy error
Work around an undefined NPY_INTERNAL_BUILD macro error

  /tmp/python-2.7.15/lib/python2.7/site-packages/numpy/core/include/numpy/npy_common.h:17:5: error: "NPY_INTERNAL_BUILD" is not defined
  cc1plus: warnings being treated as errors

when compiling with GCC 4.4.7 on RHEL 6 with -Wall -Wundef -Werror.

The NumPy issue is fixed in NumPy commit c6566b7.  This workaround will
work with or without NumPy commit c6566b7.  If the minimum version of
NumPy required by adPython is known to contain commit c6566b7, this
workaround can be removed.